version: '3.9'
services:
  web:
    restart: always
    container_name: web
    depends_on:
      - prisma-studio
    ports:
      - '3000:3000'
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    image: web
    env_file:
      - .env
  postgres:
    restart: always
    container_name: postgres
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=${POSTGRES_DATABASE}
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    env_file:
      - .env
    ports:
      - '${POSTGRES_PORT}:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
  prisma-studio:
    container_name: prisma-studio
    build:
      context: .
      dockerfile: ./packages/db/Dockerfile
    restart: unless-stopped
    image: prisma-studio
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - ${PRISMA_STUDIO_PORT}:5555

volumes:
  postgres:
    driver: local
