name: Build App
on:
  pull_request:
    branches: ['*']
  push:
    branches: ['main']
  merge_group:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 🏗 Setup repo
        uses: actions/checkout@v2

      - name: Setup Node 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: 🏗 Setup Expo and EAS
        uses: expo/expo-github-action@v7
        with:
          token: ${{ secrets.EXPO_TOKEN }}
          expo-version: latest
          eas-version: latest
          packager: npm

      - name: 🏗 Setup EAS local builds
        run: npm i -G eas-cli-local-build-plugin

      - uses: bahmutov/npm-install@v1

      - name: 👷 Build app
        run: |
          eas build --local \
            --non-interactive \
            --output=./app-build \
            --platform=android

      - name: 📱 Upload binary
        uses: actions/upload-artifact@v2
        with:
          name: app-${{ github.event.inputs.platform }}
          path: app-build
