name: CI

on:
  pull_request:
    branches: ['*']
  push:
    branches: ['main']
  merge_group:


jobs:
  build-lint:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    env:
      DATABASE_URL: 'postgresql://postgres:postgres@localhost:5432/postgres'
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - uses: bahmutov/npm-install@v1
      - name: Generate Prisma Client
        run: npx turbo db:generate

      - name: Build, lint and type-check
        run: npx turbo build lint type-check
        env:
          SKIP_ENV_VALIDATION: true
