name: Deploy

on:
  push:
    branches: ['main']

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup env
        run: cp .env.example .env
      - name: Build and publish
        uses: pennsignals/publish_docker-compose@v0.1.0
        with:
          docker_compose: 'docker-compose.build.yml'
          repo_token: '${{ secrets.GITHUB_TOKEN }}'
