name: Docker-app

on:
  push:
    branches: ['main']

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      # Log into github registry
      - name: Log into registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup env
        run: cp .env.example .env
      - name: Build the docker-compose
        run: docker compose build
      - name: List images
        run: docker images
      - name: Push images
        run: docker compose push
