name: Docker-app

on:
  push:
    branches: ['main']

env:
  POSTGRES_PORT: 5432
  PRISMA_STUDIO_PORT: 5000

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - uses: actions/checkout@v3
      - name: publish
        uses: pennsignals/publish_docker-compose@v0.1.0
        with:
          docker_compose: 'docker-compose.yml'
          repo_token: '${{ secrets.GITHUB_TOKEN }}'
