name: Cleanup Preview Deployments
on:
  pull_request:
    types:
      - closed

jobs:
  update:
    name: Cleanup Preview Channel and Branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci --ignore-scripts

      - name: Setup Expo
        uses: expo/expo-github-action@v7
        with:
          eas-version: latest
          eas-cache: false
          packager: npm
          token: ${{ secrets.EXPO_TOKEN }}

      - name: CD into expo
        run: cd ./apps/expo

      - name: Delete Channel
        run: eas channel:delete ${{ github.head_ref }} --non-interactive

      - name: Delete Branch
        run: eas branch:delete ${{ github.head_ref }} --non-interactive
