name: Preview

on:
  issue_comment:
    types: [created]
  pull_request:
    branches: [main]

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      triggered: ${{ steps.check.outputs.triggered }}
    steps:
      - uses: Rei-x/pull-request-preview-action/comment@main
        id: check
        with:
          GITHUB_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}

  run-preview:
    runs-on: ubuntu-latest
    needs: [check]
    if: ${{ needs.check.outputs.triggered == 'true' }}
    concurrency:
      group: ${{ github.event.issue.number || github.event.pull_request.number }}
      cancel-in-progress: true
    steps:
      - uses: Rei-x/pull-request-preview-action/start-preview@main
        id: tunnel-url
        with:
          GITHUB_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}
          ports: 3000,5000

      - name: Add info about build
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          append: true
          number: ${{ github.event.issue.number || github.event.pull_request.number }}
          GITHUB_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}
          message: |
            **🖼️ Preview Environment:** _Building app..._

      - name: Build app
        run: |
          cp .env.example .env
          sed -i "s/NEXTAUTH_URL.*/NEXTAUTH_URL=${{ steps.tunnel-url.outputs.url-1 }}/" .env
          npm run docker:build

      - name: Post mobile app
        uses: ./.github/expo-preview
        with:
          GITHUB_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

      - name: Add info abourt starting app
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          append: true
          number: ${{ github.event.issue.number || github.event.pull_request.number }}
          GITHUB_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}
          message: |
            **🖼️ Preview Environment:** _Launching app..._

      - name: Start app
        run: npm run docker:run -- -d

      - uses: Rei-x/pull-request-preview-action/end-preview@main
        with:
          url: ${{ steps.tunnel-url.outputs.url-1 }}
          GITHUB_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}

      - name: Close comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: success()
        with:
          number: ${{ github.event.issue.number || github.event.pull_request.number }}
          GITHUB_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}
          message: |
            🖼️ Preview Environment exceeded the maximum time of 60 minutes. 

            To start it again, comment `/preview` on this PR.

      - name: Close comment when cancelled
        uses: marocchino/sticky-pull-request-comment@v2
        if: cancelled()
        with:
          number: ${{ github.event.issue.number || github.event.pull_request.number }}
          GITHUB_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}
          message: |
            🖼️ Preview Environment was cancelled (because of newer preview or manual cancellation).

            To start it again, comment `/preview` on this PR.

      - name: Close comment when failed
        uses: marocchino/sticky-pull-request-comment@v2
        if: failure()
        with:
          number: ${{ github.event.issue.number || github.event.pull_request.number }}
          GITHUB_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}
          message: |
            🖼️ Preview Environment failed to start. You can see more info here [GitHub Action](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}). 

            To start it again, comment `/preview` on this PR.
